apiVersion: v1
kind: ConfigMap
metadata:
  name: yugabyte-tserver
  labels:
    app.kubernetes.io/name: yugabyte-tserver
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: identity-provider
    app.kubernetes.io/part-of: spp
data: {}
