{{ if .Values.debug }}
apiVersion: v1
kind: Service
metadata:
  name: yugabyte-master-debug
  labels:
    app.kubernetes.io/name: yugabyte-master
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: identity-provider
    app.kubernetes.io/part-of: spp
  annotations:
    metallb.universe.tf/allow-shared-ip: debug
spec:
  #type: LoadBalancer
  type: NodePort
  selector:
    app.kubernetes.io/name: yugabyte-master
  ports:
    - name: ui
      protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 32000
    - name: rpc
      protocol: TCP
      port: 7100
      targetPort: 7100
      nodePort: 32001
{{ end }}
