apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yugabyte-master
  labels:
    app.kubernetes.io/name: yugabyte-master
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: identity-provider
    app.kubernetes.io/part-of: spp
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: yugabyte-master
  replicas: {{ int64 .Values.replicas }}
  serviceName: yugabyte-master
  template:
    metadata:
      labels:
        app.kubernetes.io/name: yugabyte-master
        helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/component: identity-provider
        app.kubernetes.io/part-of: spp
    spec:
      imagePullSecrets:
        - name: yugabyte-master-image-pull-secret
      containers:
        - name: yugabyte-master
          image: {{ .Values.image.registry }}/{{ .Values.image.path }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 7000
            - containerPort: 7100
          envFrom:
            - configMapRef:
                name: yugabyte-master
          env:
            - name: METADATA_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MASTER_ADDRESSES
              {{- $namespace := .Release.Namespace }}
              {{- $first := true }}
              value: {{ range (untilStep 0 (int .Values.replicas) 1) }}{{ if $first }}{{ $first = false }}{{ else }},{{ end }}yugabyte-master-{{ . }}.yugabyte-master.{{ $namespace }}.svc.cluster.local:7100{{ end }}
            - name: RPC_BIND_ADDRESSES
              value: $(METADATA_NAME).yugabyte-master.{{ .Release.Namespace }}.svc.cluster.local:7100
          #readinessProbe:
          #  exec:
          #    command:
          #      - docker-healthcheck.sh
          #  initialDelaySeconds: 15
          #  periodSeconds: 15
          #  timeoutSeconds: 15
          #  failureThreshold: 20
          livenessProbe:
            exec:
              command:
                - docker-healthcheck.sh
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 15
            failureThreshold: 20
          volumeMounts:
            - name: data
              mountPath: /mnt/master
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/name: yugabyte-master
          helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
          app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
          app.kubernetes.io/instance: {{ .Release.Name | quote }}
          app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
          app.kubernetes.io/component: identity-provider
          app.kubernetes.io/part-of: spp
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.storage.className | quote }}
        resources:
          requests:
            storage: {{ .Values.storage.size | quote }}
