@base=https://identity-provider.minikube

### SignIn

POST {{base}}/identity-provider/v1/auth/sign-in
Content-Type: application/json

{
  "username": "superuser",
  "password": "pass",
  "scopes": "api"
}
