@base=https://identity-provider.minikube
@token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjMyNkNFNkJBMjIwM0RDRDg1NzBDQURCOEM0QzFFMEU1NTJCNDlDNUEiLCJ4NXQiOiJNbXptdWlJRDNOaFhESzI0eE1IZzVWSzBuRm8iLCJ0eXAiOiJhdCtqd3QifQ.eyJpc3MiOiJodHRwczovL2lkZW50aXR5LXByb3ZpZGVyLm1pbmlrdWJlIiwibmJmIjoxNzIyMTc2OTg4LCJpYXQiOjE3MjIxNzY5ODgsImV4cCI6MTcyMjE4MDU4OCwiYXVkIjoiaHR0cHM6Ly9pZGVudGl0eS1wcm92aWRlci5taW5pa3ViZSIsInNjb3BlIjpbImFwaSIsIm9wZW5pZCIsIm9mZmxpbmVfYWNjZXNzIl0sImNsaWVudF9pZCI6ImlkZW50aXR5X3Byb3ZpZGVyIiwic3ViIjoiZDQ0MWZmOGIwNTlhNGYxNjlmNTM4YTFlMWU5MDIyNmMiLCJhdXRoX3RpbWUiOjE3MjIxNzY5NjAsImlkcCI6ImxvY2FsIiwianRpIjoiRUQwQzY3ODlGOTJENzlDOUI2OTBGOEE3QUQyOUMxMjUifQ.EAyr9x89O-ODeomaTDztY90vJpXYt_STDC41egYKtvSf_KGjfd6vCPvJh-kCMHCg_S_r470LQErGrYRDT6VCftAAh3cvWUV2ZDSih1KdetmTaSuhaheqZy2pNT-6JdHw2ks71dXlkF_pmJA31QmHdbAalYEt2RR_ih2ff1JSLFKd8ZStb3NV4-AIMhsupNmuq45JyF2OPkjl97jMAWiYnqHrm_S-oFNfqO-MTLZ4CndawVwPkDIE4uMRkAd_synOUHlVRkAKqI70jKcs9U0jqdm-YpbzoPoeXo_Z3NflI6jsZG_JZE6R_bVqukrkUP_n0xGdWVo5VV-o1azA0FyZSg

### Create

POST {{base}}/identity-provider/v1/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "user1",
  "password": "pass"
}
