@base=https://localhost:34008
@token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjM2N0ZGRDczQTg5QjhFOTg0OUI4Mjc4MDE5NDE2OEFDREI1NTVFNzYiLCJ4NXQiOiJObl85YzZpYmpwaEp1Q2VBR1VGb3JOdFZYblkiLCJ0eXAiOiJhdCtqd3QifQ.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDozNDAwMCIsIm5iZiI6MTcxNTA1ODU4NSwiaWF0IjoxNzE1MDU4NTg1LCJleHAiOjE3MTUwNjIxODUsImF1ZCI6IlNwcC5JZGVudGl0eVByb3ZpZGVyQVBJIiwic2NvcGUiOlsiYXBpIiwib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiXSwiY2xpZW50X2lkIjoicXdlIiwic3ViIjoiOTgxMzQyYzctNzliYi00YmIzLTk4N2UtZGQzNTNiODkyNGU4IiwiYXV0aF90aW1lIjoxNzE1MDU4NTg1LCJpZHAiOiJsb2NhbCIsImp0aSI6IkRBNDJFNzU1NURCMzc2OEFBQTdGOTVBRTFBOTk2RkEyIn0.hRmnUbh8kuGD6IUvGqCfUsuYMCJWN2evCFAwi3wi5v1e-aji_orofmAarETZVYrNkckshMvJtXlrasrO9NrA8VaUnzmDFkN7huJaUDOJc5GpkpA59tBDV7F-kscnMYCJ66ZR2qcJAO3lw_aa5CA0UlvtdFykMtIa3PODtZCWzxe6b1aRXy06tLM4OWkLDCS0xExr0EGfN9Av6ZshpLox09MIx1SRuAZH-i9KafMtp7IN6HhLXD8wAOEz6wtdB3PkvAM3JgWZ02vcdWTrYBRsPjWLf6RW5N58S7G3-PMlRIreYX7b0NzbDLsQW35XpFdcNIpzsqMHBmhDUgWgM5mgfw

### Token client_credentials

POST {{base}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=api&client_id=qwe&client_secret=123

### Authorize

GET {{base}}/connect/authorize?client_id=qwe&response_type=code&redirect_uri=https%3A%2F%2Flocalhost%3A34008%2Fv1%2Fauth%2Fcallback&scope=api%20openid%20offline_access&code_challenge=YBO3Dq5oQmYNID_UmD8gVPTA0EACOeifukgyQgCjdjg&code_challenge_method=S256
Authorization: Bearer {{token}}

### Token authorization_code

POST {{base}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&scope=api openid offline_access&client_id=qwe&client_secret=123&redirect_uri=https%3A%2F%2Flocalhost%3A34008%2Fv1%2Fauth%2Fcallback&code_verifier=489cd5dbc708c7e541de4d7cd91ce6d0f1613573b7fc5b40d3942ccb9555cf35&code=CCB721F7493E414BDDF786079F27E6DA701883C6324D312284F1D9A74D54AF8E-1
