@base=https://identity-provider.minikube
@token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjgzOTM1NDdCRUU0RDRFNzBFMDNBNzMwRTQ4NEVBMzAzQTQzRDk0NjIiLCJ4NXQiOiJnNU5VZS01TlRuRGdPbk1PU0U2akE2UTlsR0kiLCJ0eXAiOiJhdCtqd3QifQ.eyJpc3MiOiJodHRwczovL2lkZW50aXR5LXByb3ZpZGVyLm1pbmlrdWJlIiwibmJmIjoxNzIyMjYyNDk4LCJpYXQiOjE3MjIyNjI0OTgsImV4cCI6MTcyMjI2NjA5OCwiYXVkIjoiaHR0cHM6Ly9pZGVudGl0eS1wcm92aWRlci5taW5pa3ViZSIsInNjb3BlIjpbImFwaSJdLCJjbGllbnRfaWQiOiJpZGVudGl0eV9wcm92aWRlciIsInN1YiI6ImQ0NDFmZjhiMDU5YTRmMTY5ZjUzOGExZTFlOTAyMjZjIiwiYXV0aF90aW1lIjoxNzIyMjYyNDk4LCJpZHAiOiJsb2NhbCIsImp0aSI6IkIyNjEyOTQxMzUwMDUwOTFCREVGRTlDMjk5OTBBRTRGIn0.blEXs6riJ2jg5293zkVc0zeQxbkYtHMNXgabZHHQUkx3FEevRJxXIIvZmA5qnIBK8LhNy8mHKV-E94xZU5T0Z1y_m9nMINJAI1hyPsjvmt24RHZtI__08uFoNxscjFkirZT1xxGmH-B--kHSeaFlmPStuTMMBtFG2AMk82t0pEXyWM6LS4DGHLEQ82ur9hrfY_zZJBhIIpwj54liH0d3XUhw-hyIpXc8NJA2Ok6Xfwm8AN3E1KsTWXjSdErcSTeNnowNLA9yA2E9UO0tpcLC2rOYofJ75eJ0aXHuEabb8U_3j4qGz-5elgpyeh2318W3qtJzDDxcqh4vWgT6rw9NAA

### Token client_credentials

POST {{base}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=api&client_id=identity_provider&client_secret=secret

### Authorize

GET {{base}}/connect/authorize?client_id=identity_provider&response_type=code&redirect_uri=https%3A%2F%2Fidentity-provider.minikube%2Fidentity-provider%2Fv1%2Fauth%2Fcallback&scope=api%20openid%20offline_access&code_challenge=YBO3Dq5oQmYNID_UmD8gVPTA0EACOeifukgyQgCjdjg&code_challenge_method=S256
Authorization: Bearer {{token}}

### Token authorization_code

POST {{base}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&scope=api openid offline_access&client_id=identity_provider&client_secret=secret&redirect_uri=https%3A%2F%2Fidentity-provider.minikube%2Fidentity-provider%2Fv1%2Fauth%2Fcallback&code_verifier=489cd5dbc708c7e541de4d7cd91ce6d0f1613573b7fc5b40d3942ccb9555cf35&code=D9AC700D8AD2031099CEFD4A0720331214C2AB5B8B49AD8CFB0C8818945E99D8-1
