version: '3.8'

services:
  spp_docker_registry:
    container_name: spp_docker_registry
    image: registry:2
    restart: always
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:51443
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/localhost.crt
      REGISTRY_HTTP_TLS_KEY: /certs/localhost.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    ports:
      - '51443:51443'
    volumes:
      - ./certificates:/certs
      - ./auth:/auth
      - ./.docker/spp_docker_registry:/var/lib/registry
