---
openapi: 3.1.0
info:
  title: IdentityProvider Users API
  version: 1.0.0

paths:

  /identity-provider/v1/users:
    post:
      description: Create user.
      operationId: Create
      tags:
        - Users
      security:
        - bearerAuth: []
      requestBody:
        description: Create user request.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'
          headers:
            Location:
              description: Created resource location.
              schema:
                type: string
        '400':
          description: |
            Bad request.
            - identityProvider.duplicateUsername
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '401':
          $ref: '#/components/responses/UnauthorizedErrorResponse'
        '403':
          $ref: '#/components/responses/ForbiddenErrorResponse'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:

    UnauthorizedErrorResponse:
      description: Unauthorized.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    ForbiddenErrorResponse:
      description: Forbidden.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    DefaultErrorResponse:
      description: Unexpected error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

  schemas:

    CreateUserRequest:
      description: Create user request.
      type: object
      required:
        - username
        - password
      properties:
        username:
          description: Username.
          type: string
        password:
          description: Password.
          type: string

    CreateUserResponse:
      description: Create user response.
      type: object
      required:
        - id
      properties:
        id:
          description: User identifier.
          type: string

    ProblemDetails:
      $ref: './common.errors.yaml#/components/schemas/ProblemDetails'
