version: '3.8'

networks:
  spp_network:
    name: spp_network
    driver: bridge

services:
  
  spp_yugabyte_master_1:
    image: ${SPP_DOCKER_REGISTRY_ADDRESS:-localhost:51443}/spp/yugabyte/master:${SPP_SERVICES_YUGABYTE_VERSION:-0.0.1}
    container_name: spp_yugabyte_master_1
    environment:
      SERVICE_7000_NAME: spp_yugabyte_master_1
    command:
      - '/home/yugabyte/bin/yb-master'
      - '--fs_data_dirs=/mnt/master'
      - '--master-addresses=spp_yugabyte_master_1:7100,spp_yugabyte_master_2:7100'
      - '--rpc_bind_addresses=spp_yugabyte_master_1:7100'
      - '--replication_factor=1'
    volumes:
      - ./.docker/spp_yugabyte_master_1/data:/mnt/master
    networks:
      - spp_network
    ports:
      - '34000:7000'
      - '34001:7100'
  
  spp_yugabyte_master_2:
    image: ${SPP_DOCKER_REGISTRY_ADDRESS:-localhost:51443}/spp/yugabyte/master:${SPP_SERVICES_YUGABYTE_VERSION:-0.0.1}
    container_name: spp_yugabyte_master_2
    environment:
      SERVICE_7000_NAME: spp_yugabyte_master_2
    command:
      - '/home/yugabyte/bin/yb-master'
      - '--fs_data_dirs=/mnt/master'
      - '--master-addresses=spp_yugabyte_master_1:7100,spp_yugabyte_master_2:7100'
      - '--rpc_bind_addresses=spp_yugabyte_master_2:7100'
      - '--replication_factor=1'
    volumes:
      - ./.docker/spp_yugabyte_master_2/data:/mnt/master
    networks:
      - spp_network
    ports:
      - '34002:7000'
      - '34003:7100'
  
  spp_yugabyte_tserver_1:
    image: ${SPP_DOCKER_REGISTRY_ADDRESS:-localhost:51443}/spp/yugabyte/tserver:${SPP_SERVICES_YUGABYTE_VERSION:-0.0.1}
    container_name: spp_yugabyte_tserver_1
    environment:
      SERVICE_5433_NAME: ysql
      SERVICE_9042_NAME: ycql
      SERVICE_6379_NAME: yedis
      SERVICE_9000_NAME: spp_yugabyte_tserver_1
    command:
      - '/home/yugabyte/bin/yb-tserver'
      - '--fs_data_dirs=/mnt/tserver'
      - '--start_pgsql_proxy'
      - '--rpc_bind_addresses=spp_yugabyte_tserver_1:9100'
      - '--tserver_master_addrs=spp_yugabyte_master_1:7100,spp_yugabyte_master_2:7100'
      - '--ysql_enable_auth'
    volumes:
      - ./.docker/spp_yugabyte_tserver_1/data:/mnt/tserver
    networks:
      - spp_network
    ports:
      - '34004:5433'
      - '34005:9100'
    #depends_on:
    #  - spp_yugabyte_master_1

  spp_yugabyte_tserver_2:
    image: ${SPP_DOCKER_REGISTRY_ADDRESS:-localhost:51443}/spp/yugabyte/tserver:${SPP_SERVICES_YUGABYTE_VERSION:-0.0.1}
    container_name: spp_yugabyte_tserver_2
    environment:
      SERVICE_5433_NAME: ysql
      SERVICE_9042_NAME: ycql
      SERVICE_6379_NAME: yedis
      SERVICE_9000_NAME: spp_yugabyte_tserver_2
    command:
      - '/home/yugabyte/bin/yb-tserver'
      - '--fs_data_dirs=/mnt/tserver'
      - '--start_pgsql_proxy'
      - '--rpc_bind_addresses=spp_yugabyte_tserver_2:9100'
      - '--tserver_master_addrs=spp_yugabyte_master_1:7100,spp_yugabyte_master_2:7100'
      - '--ysql_enable_auth'
    volumes:
      - ./.docker/spp_yugabyte_tserver_2/data:/mnt/tserver
    networks:
      - spp_network
    ports:
      - '34006:5433'
      - '34007:9100'
    #depends_on:
    #  - spp_yugabyte_master_1
