apiVersion: v1
kind: Secret
metadata:
  name: identity-provider-client-secret
  labels:
    app.kubernetes.io/name: identity-provider
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: identity-provider
    app.kubernetes.io/part-of: spp
type: Opaque
data:
  value: {{ .Values.config.authentication.clientSecret.value | b64enc | quote }}
