---
openapi: 3.1.0
info:
  title: Authorization Users API
  version: 1.0.0

paths:

  /v1/users/{id}/roles/{roleId}:
    parameters:
      - name: id
        in: path
        required: true
        description: User identifier.
        schema:
          type: string
      - name: roleId
        in: path
        required: true
        description: Role identifier.
        schema:
          type: string
    put:
      description: Assign role to user.
      operationId: AssignRole
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Role assigned.
        '400':
          $ref: '#/components/responses/BadRequestErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedErrorResponse'
        '403':
          $ref: '#/components/responses/ForbiddenErrorResponse'
        '404':
          $ref: '#/components/responses/NotFoundErrorResponse'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
    delete:
      description: Unassign role from user.
      operationId: UnassignRole
      tags:
        - Users
      responses:
        '204':
          description: Role unassigned.
        '400':
          $ref: '#/components/responses/BadRequestErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedErrorResponse'
        '403':
          $ref: '#/components/responses/ForbiddenErrorResponse'
        '404':
          $ref: '#/components/responses/NotFoundErrorResponse'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:

    BadRequestErrorResponse:
      description: Bad request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    UnauthorizedErrorResponse:
      description: Unauthorized.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    ForbiddenErrorResponse:
      description: Forbidden.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    NotFoundErrorResponse:
      description: Not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    DefaultErrorResponse:
      description: Unexpected error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

  schemas:

    ProblemDetails:
      $ref: './common.errors.yaml#/components/schemas/ProblemDetails'
